export const END_POINTS = {
    oauth: {
        register: 'auth/register',
        login: 'login',
        refresh: 'auth/refresh',
        logout: 'logout',
        signup: 'keycloak/user/create',
        active: 'auth/active',
        create: 'auth/create',
        find: 'find',
        reset: 'auth/reset',
        company:'company',
    },
    setup: {
        sectionDetailEnds:'sectionDetailEnds',
        sectionDetails:'sectionDetails',
        sections:'sections',
        parentModule:'parent-module',
        companyUserRole:'company-user-role',
        module:'module',
        asociaciones:'asociaciones',
        asociacion:'asociacion',
        service:'service',
        municipalidad:'municipalidad',
        company:'company',
        listCompany: 'listCompany',
        companyuser:'companyuser',
        companyuseradmin:'company-user-admin',
        ubigeoSunat:'ubigeo-sunat',
        role: 'role',
        //client: 'cliente',
        product: 'producto',
        category: 'categoria',
        accesRole: 'acceso-rol',
        person: 'persona',
        institution: 'institucion',
        subsidiary: 'filial',
        faculty: 'facultad',
        prefessionalSchool: 'escuela-profesional',
        cycle: 'ciclo',
        group: 'grupo',
        jerarquia: "gerarquia",
        menu: "menu",
        users: 'keycloak/user',
        access: 'acceso',
        access_parent: 'acceso-padres',
    },
    catalog:{
        unitMeasurement: 'unit-measurements',
        categories: 'categories',
        products: 'products',
        productDynamic: 'product-accounting-dynamics',
        serialFlows: 'serial-flows',
    },
    client:{
        documentTypes: 'document-types',
        entityTypes: 'entity-types',
        services: 'services',
        entities: 'entities',
    },
    reports:{
        warranties: 'series',
        profitability: 'profitability',
    },
    accountant: {
        contAsientos: 'cont-asientos',
    },
    accounting:{
        accountingAccountClass:'accounting-account-classes',
        typeDocument:'type-documents',
        typeAfeectation:'type-affectations',
        areas:'areas',
        stores:'stores',
        accountingPlan:"accounting-plan",
        accountingDynamics:'accounting-dynamics',
    },
    buys:{
        purchases: 'purchases',
        entitiesCompanyP: 'entities-company',
    },
    product:{
        product: 'emprendedor-service',
        emprendedor:'emprendedor',
        reservas: 'reservas',
    },
    payments:{
        payments: 'payments',
        operationTypes: 'operation-types',
        paymentsMethods: 'payment-methods',
        paymentsTypes: 'payment-types',
    },
    sales:{
        sales: 'sale',
        payment: 'payment',
        prices: 'prices',
        barCode: 'barcode',
        priceDetails: 'price-details',
        entitiesCompanyC: 'entities-company',
        creditNoteTypes: 'credit-note-types',

    },
    warehouseMovement:{
        warehouseMovement: 'warehouse-movement',
        inventories: 'inventories',
        kardex: 'kardex',
        series: 'series',
        lots: 'lots',
    },
    event: {
        event: 'evento',
    },
    attendance: {
        attendance: 'asistencia',
    },
    /*****---------- */
    userModules: 'user-modules',
    validTokensOauth: 'valid-tokens-oauth',
    orders: 'messages',
};
